provincias=[{"nombre":"Buenos Aires","factor": 4.125,"latitud":-36.7},
            {"nombre":"Catamarca","factor": 5.083,"latitud":-27.3},
            {"nombre":"Chaco","factor": 4.25,"latitud":-26.4},
            {"nombre":"Chubut","factor":3.875,"latitud":-43.8},
            {"nombre":"Cordoba","factor": 4.25,"latitud":-32.1},
            {"nombre":"Corrientes","factor": 4.542,"latitud":-28.8},
            {"nombre":"Entre Ríos","factor":4.33,"latitud":-32.06},
            {"nombre":"Formosa","factor": 4.25,"latitud":-24.9},
            {"nombre":"Jujuy","factor":5.708,"latitud":-23.3},
            {"nombre":"La Pampa","factor":4.125,"latitud":-37.1},
            {"nombre":"La Rioja","factor":5.083,"latitud":-29.7},
            {"nombre":"Mendoza","factor":4.792,"latitud":-34.6},
            {"nombre":"Misiones","factor": 4.125,"latitud":-26.9},
            {"nombre":"Neuquén","factor":4.458,"latitud":-38.6},
            {"nombre":"Río Negro","factor": 4.167,"latitud":-40.4},
            {"nombre":"Salta","factor": 4.042,"latitud":-24.3},
            {"nombre":"San Juan","factor": 4.583,"latitud":-30.9},
            {"nombre":"San Luis","factor":4.5,"latitud":-33.8},
            {"nombre":"Santa Cruz","factor":3.292,"latitud":-48.8},
            {"nombre":"Santa Fe","factor":4.375,"latitud":-30.8},
            {"nombre":"Santiago del Estero","factor":4.25,"latitud":-27.8},
            {"nombre":"Tierra del Fuego, Antártida e Islas del Atlántico Sur","factor":2.67,"latitud":-82.5},
            {"nombre":"Tucuman","factor":4,"latitud":-26.9}]